version: '3.8'

services:
  ldap:
    build: ./ldap
    container_name: ldap
      #user: root
    environment:
      - LDAP_ROOT=dc=labcas,dc=jpl,dc=nasa,dc=gov
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_LOGLEVEL=stats,stats2,config,acl
      - LDAP_DEBUG=true
      - BITNAMI_DEBUG=true
      - LDAP_CUSTOM_LDIF_DIR=/container-init.d
    ports:
      - "389:389"
      - "1389:1389"
    volumes:
      - ./ldap/custom_ldifs:/container-init.d
    networks:
      - labcas-net

  labcas-backend:
    build: ./labcas-backend
    container_name: labcas-backend
    depends_on:
      - ldap
    environment:
      - LABCAS_HOME=/tmp/labcas
    ports:
      - "8080:8080"  # Map the backend service port
      - "8444:8444"  # Map the backend service port
    volumes:
      - ./labcas-backend/labcas.properties:/root/labcas.properties
      - ./labcas-backend/server.xml:/tmp/labcas/apache-tomcat/conf/server.xml
    networks:
      - labcas-net
    command: >
      /bin/bash -c "
      sleep 30 &&
      /tmp/labcas/start.sh &&
      tail -f /dev/null
      "

  labcas-ui:
    build: ./labcas-ui
    container_name: labcas-ui
    depends_on:
      - labcas-backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./labcas-ui/environment.cfg:/usr/local/apache2/htdocs/labcas-ui/assets/conf/environment.cfg
    networks:
      - labcas-net

networks:
  labcas-net:
