#!/usr/bin/env python3
"""Map simple genomic input into LinkML Datasetlevel metadata."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any, Dict

import yaml


def _load_input(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def _normalize_source(raw: Dict[str, Any]) -> Dict[str, Any]:
    response = raw.get("response")
    if isinstance(response, dict):
        docs = response.get("docs")
        if isinstance(docs, list):
            for item in docs:
                if isinstance(item, dict):
                    return item
    return raw


def _defaulted(raw: Dict[str, Any], key: str, default: str) -> str:
    value = raw.get(key)
    if value is None:
        return default
    if isinstance(value, list):
        for item in value:
            text = str(item).strip()
            if text:
                return text
        return default
    text = str(value).strip()
    return text if text else default


def _to_dataset_id(value: str, default: str = "GENOMIC-HELLO-001") -> str:
    cleaned = re.sub(r"[^A-Za-z0-9]+", "-", value).strip("-").upper()
    return cleaned if cleaned else default


def _mapped_assay_technique(raw: Dict[str, Any]) -> str:
    direct = _defaulted(raw, "assay_technique", "")
    if direct:
        return direct
    candidate = _defaulted(raw, "SequencingAssayType", _defaulted(raw, "AssayType", ""))
    lowered = candidate.lower()
    if any(token in lowered for token in ["dna", "sequenc", "hybrid", "amplicon", "duplex"]):
        return "DNA_sequencing"
    if any(token in lowered for token in ["rna", "transcript"]):
        return "RNA_sequencing"
    return "DNA_sequencing"


def _map_to_datasetlevel(raw: Dict[str, Any]) -> Dict[str, Any]:
    src = _normalize_source(raw)
    dataset_title = _defaulted(
        src,
        "dataset_title",
        _defaulted(
            src, "DatasetName", _defaulted(src, "CollectionName", "Genomic Hello World Dataset")
        ),
    )
    dataset_description = _defaulted(
        src,
        "dataset_description",
        _defaulted(
            src,
            "CollectionDescription",
            "Minimal genomic metadata payload generated by genome_mission mapper.",
        ),
    )
    dataset_id = _defaulted(
        src, "dataset_id", _defaulted(src, "dataset_ID", _defaulted(src, "DatasetId", ""))
    )
    if not dataset_id:
        dataset_id = _to_dataset_id(_defaulted(src, "CollectionId", dataset_title))

    return {
        # Required slots in Datasetlevel
        "dataset_title": dataset_title,
        "dataset_description": dataset_description,
        "dataset_ID": dataset_id,
        # Useful optional slots
        "assay_technique": _mapped_assay_technique(src),
        "external_organization_name": _defaulted(src, "Consortium", ""),
        "data_custodian_name": _defaulted(src, "DataCustodian", ""),
        "data_custodian_email": _defaulted(src, "DataCustodianEmail", ""),
        "data_submitter": _defaulted(src, "LeadPoC", ""),
    }


def _write_output(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        yaml.safe_dump(payload, fh, sort_keys=False)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Map genomic hello-world input into LinkML Datasetlevel metadata."
    )
    parser.add_argument(
        "--input-file",
        default="/data/raw/genomic_helloworld/input.json",
        help="Path to source JSON payload.",
    )
    parser.add_argument(
        "--output-file",
        default="/data/staging/genomic_helloworld/datasetlevel.yaml",
        help="Path to mapped Datasetlevel YAML output.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    src = Path(args.input_file)
    dst = Path(args.output_file)

    if not src.exists():
        raise FileNotFoundError(f"Input file not found: {src}")

    mapped = _map_to_datasetlevel(_load_input(src))
    _write_output(dst, mapped)
    print(f"Wrote mapped Datasetlevel payload to {dst}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
