# LabCAS Properties
# =================

# QUIP 
# ----
quipSubmitImageUrl=https://54.164.233.119:12345/submitData
quipViewImageUrl=https://54.164.233.119/camicroscope/osdCamicroscope.php


# Thumbnails
# ----------
thumbnailsRootDir=/tmp/data/var/microscopic-images/
thumbnailsRootUrl=https://unknown/microscopic-images/


# OHIF
# ----
ohifSubmitImageUrl=https://54.164.233.119:23456/instances
ohifViewImageUrl=https://54.164.233.119/viewer/
ohifUsername=orthanc
ohifPassword=orthanc


# LabCAS Data Access API
# ----------------------
#
# Settings directly related to the functioning of LabCAS
#
# Common Settings
# ~~~~~~~~~~~~~~~
#
# Now we have our own NIST branch in LDAP
#
# Use these settings for the OpenLDAP server built into this Docker composition:

dataAccessApiBaseUrl=https://localhost/nist/data-access-api/download?id=
ldapAdminDn=cn=admin,dc=labcas,dc=jpl,dc=nasa,dc=gov
solrUrl=https://localhost:8984/solr
superOwnerPrincipal=cn=Super User,ou=groups,dc=labcas,dc=jpl,dc=nasa,dc=gov
publicOwnerPrincipal=cn=All Users,ou=groups,dc=labcas,dc=jpl,dc=nasa,dc=gov                                                                                                                                                                     
jwtSecret=m0stS3cret
ldapUsersUri=ldaps://ldap:1636/ou=users,dc=labcas,dc=jpl,dc=nasa,dc=gov
ldapGroupsUri=ldaps://ldap:1636/ou=groups,dc=labcas,dc=jpl,dc=nasa,dc=gov
ldapAdminPassword=secret


# Use with EDRN Directory Service
# -------------------------------
#
# To use the offical EDRN Directory Service, comment-out the above settings and then un-
# comment-out the following settings, replacing the two `REPLACE_WITH_…` strings with
# preferred values:
#
# dataAccessApiBaseUrl=https://localhost/nist/data-access-api/download?id=
# ldapAdminDn=uid=admin,ou=system
# solrUrl=https://localhost:8984/solr
# superOwnerPrincipal=cn=Super User,ou=groups,o=NIST
# publicOwnerPrincipal=cn=All Users,ou=groups,o=NIST
# jwtSecret=REPLACE_WITH_SECRET
# ldapUsersUri=ldaps://edrn-ds.jpl.nasa.gov/ou=users,o=NIST
# ldapGroupsUri=ldaps://edrn-ds.jpl.nasa.gov/ou=groups,o=NIST
# ldapAdminPassword=REPLACE_WITH_ACTUAL_PASSWORD
