[SERVICE]
    Flush        1
    Daemon       Off
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*-json.log
    Parser            docker
    Tag               docker.*
    Refresh_Interval  5
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On

[FILTER]
    Name   grep
    Match  docker.*
    Regex  container_name  ldap$

[OUTPUT]
    Name   file
    Match  docker.*
    Path   /logs
    File   ldap.stdout.log
